packages:
  core: !include sensorcube-rc.yaml

esphome:
  project:
    version: dev

# Sets up the improv via serial client for Wi-Fi provisioning.
improv_serial:

dashboard_import:
  package_import_url: github://Tweako/sensorcube/sensorcube-rc.yaml@main
