packages:
  core: !include sensorcube.yaml

esphome:
  project:
    version: dev

# Sets up the improv via serial client for Wi-Fi provisioning.
improv_serial:

safe_mode:

ota:
  password: ""

web_server:
  port: 80

dashboard_import:
  package_import_url: github://Tweako/sensorcube/sensorcube.yaml@main