packages:
  core: !include sensorcube_rc.yaml

esphome:
  project:
    version: dev

# Sets up the improv via serial client for Wi-Fi provisioning.
improv_serial:

update:
  - platform: http_request
    id: update_http_request
    name: "SensorCube Update"
    source: https://github.com/Tweako/SensorCube/releases/latest/download/sensorcube_rc.manifest.json

dashboard_import:
  package_import_url: github://Tweako/sensorcube/sensorcube_rc.yaml@main