substitutions:
  name: sensorcube
  friendly_name: SensorCube
  num_leds: "12" # Number of LEDs in the ring
  hidden_ssid: "False"
  log_level: INFO

esphome:
  name: "${name}"
  friendly_name: "${friendly_name}"
  name_add_mac_suffix: true

packages:
  device_base: !include components/sensorcube_base.yaml
  network_base: !include components/network.yaml
  dht22_base: !include components/dht22.yaml
  ens160_base: !include components/ens160.yaml
  ld2450_base: !include components/ld2450.yaml
  ledring_base: !include components/ledring.yaml
  ldr_base: !include components/ldr.yaml
  led_air_quality: !include components/led_air_quality.yaml
  diagnostics: !include components/diagnostics.yaml

# Standaard SensorCube configuratie met alle functies