# Diagnostic sensors for system monitoring and troubleshooting

sensor:
  # WiFi signal strength
  - platform: wifi_signal
    name: "WiFi Signal"
    id: wifi_signal_sensor
    update_interval: 60s
    entity_category: diagnostic
    icon: "mdi:wifi"
    unit_of_measurement: "dBm"
    accuracy_decimals: 0
    
  # ESP32 internal temperature
  - platform: internal_temperature
    name: "ESP32 Temperature"
    id: esp32_temperature
    disabled_by_default: True
    entity_category: diagnostic
    unit_of_measurement: "°C"
    device_class: temperature
    accuracy_decimals: 1
    icon: "mdi:thermometer"
    update_interval: 30s
    filters:
      - sliding_window_moving_average:
          window_size: 5
          send_every: 5

binary_sensor:
  # Status of connection
  - platform: status
    name: "Status"
    id: system_status
    entity_category: diagnostic
