# ENS160 Air Quality sensor with improved calibration and documentation

substitutions:
  # ENS160 configuration
  ens160_address: "0x53"
  ens160_update_interval: "60s"
  
  # AHT20 compensation sensor configuration
  aht20_address: "0x38"
  aht20_temp_offset: "-7"  # Offset due to ENS160 heat dissipation
  aht20_hum_offset: "5"    # Offset due to ENS160 heat dissipation
  
  # ENS160 calibration
  ens160_eco2_offset: "-100"  # Based on comparison with Sensirion SCD40
  ens160_eco2_window_size: "15"
  ens160_eco2_send_every: "15"

sensor:
  - platform: ens160_i2c
    address: ${ens160_address}
    update_interval: ${ens160_update_interval}
    aqi:
      name: "Air Quality Index"
      id: ens160_aqi
      icon: "mdi:air-filter"
      entity_category: ""
    eco2:
      name: "eCO2"
      id: ens160_eco2
      icon: "mdi:molecule-co2"
      entity_category: ""
      filters:
        - offset: ${ens160_eco2_offset} # Based on comparison with Sensirion SCD40
        - sliding_window_moving_average: # Smooth out the values
            window_size: ${ens160_eco2_window_size}
            send_every: ${ens160_eco2_send_every}
        - lambda: |-
            // Ensure eCO2 does not become negative
            if (x < 0) {
              return 0;
            } else if (x > 65000) {
              // Cap extreme values
              ESP_LOGW("ens160", "eCO2 value very high: %.0f ppm", x);
              return 65000;
            } else {
              return x;
            }
    tvoc:
      name: "TVOC"
      id: ens160_tvoc
      icon: "mdi:chemical-weapon"
      entity_category: ""
      filters:
        - lambda: |-
            // Sanity check for TVOC values
            if (x < 0 || x > 65000) {
              ESP_LOGW("ens160", "TVOC value out of range: %.0f ppb", x);
              return {};
            }
            return x;
    compensation:
      temperature: id_temperature_sensor
      humidity: id_humidity_sensor
      
  # AHT20 sensor for temperature and humidity compensation
  - platform: aht10
    variant: AHT20
    address: ${aht20_address}
    update_interval: ${ens160_update_interval}
    temperature:
      id: id_temperature_sensor
      name: "ENS160+AHT20 Temperature"
      internal: true
      filters:
        - offset: ${aht20_temp_offset} # Offset due to ENS160 heat dissipation
        - lambda: |-
            if (x < -40.0 || x > 80.0) {
              ESP_LOGW("aht20", "Temperature out of range: %.1f°C", x);
              return {};
            }
            return x;
    humidity:
      id: id_humidity_sensor
      name: "ENS160+AHT20 Humidity"
      internal: true
      filters:
        - offset: ${aht20_hum_offset} # Offset due to ENS160 heat dissipation
        - lambda: |-
            if (x < 0.0 || x > 100.0) {
              ESP_LOGW("aht20", "Humidity out of range: %.1f%%", x);
              return {};
            }
            return x;

# Text sensor for readable air quality status
text_sensor:
  - platform: template
    name: "Air Quality"
    id: air_quality_description
    icon: "mdi:air-filter"
    lambda: |-
      if (isnan(id(ens160_aqi).state)) {
        return {"Unknown"};
      }
      int aqi = (int)id(ens160_aqi).state;
      
      if (aqi == 1) {
        return {"Excellent"};
      } else if (aqi == 2) {
        return {"Good"};
      } else if (aqi == 3) {
        return {"Fair"};
      } else if (aqi == 4) {
        return {"Poor"};
      } else if (aqi == 5) {
        return {"Unhealthy"};
      } else {
        return {"Unknown"};
      }
    update_interval: 60s
