# ENS160 Air Quality sensor met verbeterde kalibratie en documentatie

substitutions:
  # ENS160 configuratie
  ens160_address: "0x53"
  ens160_update_interval: "60s"
  
  # AHT20 compensatie sensor configuratie
  aht20_address: "0x38"
  aht20_temp_offset: "-7"  # Offset door warmte van ENS160
  aht20_hum_offset: "5"    # Offset door warmte van ENS160
  
  # ENS160 kalibratie
  ens160_eco2_offset: "-100"  # Gebaseerd op vergelijking met Sensirion SCD40
  ens160_eco2_window_size: "15"
  ens160_eco2_send_every: "15"

sensor:
  - platform: ens160_i2c
    address: ${ens160_address}
    update_interval: ${ens160_update_interval}
    aqi:
      name: "Luchtkwaliteit Index"
      id: ens160_aqi
      icon: "mdi:air-filter"
      entity_category: ""
    eco2:
      name: "eCO2"
      id: ens160_eco2
      icon: "mdi:molecule-co2"
      entity_category: ""
      filters:
        - offset: ${ens160_eco2_offset} # Gebaseerd op vergelijking met Sensirion SCD40
        - sliding_window_moving_average: # Smooth out the values
            window_size: ${ens160_eco2_window_size}
            send_every: ${ens160_eco2_send_every}
        - lambda: |-
            // Zorg ervoor dat eCO2 niet negatief wordt
            if (x < 0) {
              return 0;
            } else if (x > 65000) {
              // Cap extreme waarden
              ESP_LOGW("ens160", "eCO2 waarde zeer hoog: %.0f ppm", x);
              return 65000;
            } else {
              return x;
            }
    tvoc:
      name: "TVOC"
      id: ens160_tvoc
      icon: "mdi:chemical-weapon"
      entity_category: ""
      filters:
        - lambda: |-
            // Sanity check voor TVOC waarden
            if (x < 0 || x > 65000) {
              ESP_LOGW("ens160", "TVOC waarde buiten bereik: %.0f ppb", x);
              return {};
            }
            return x;
    compensation:
      temperature: id_temperature_sensor
      humidity: id_humidity_sensor
      
  # AHT20 sensor voor temperatuur en luchtvochtigheid compensatie
  - platform: aht10
    variant: AHT20
    address: ${aht20_address}
    update_interval: ${ens160_update_interval}
    temperature:
      id: id_temperature_sensor
      name: "ENS160+AHT20 Temperature"
      internal: true
      filters:
        - offset: ${aht20_temp_offset} # Offset door warmte van ENS160
        - lambda: |-
            if (x < -40.0 || x > 80.0) {
              ESP_LOGW("aht20", "Temperatuur buiten bereik: %.1f°C", x);
              return {};
            }
            return x;
    humidity:
      id: id_humidity_sensor
      name: "ENS160+AHT20 Humidity"
      internal: true
      filters:
        - offset: ${aht20_hum_offset} # Offset door warmte van ENS160
        - lambda: |-
            if (x < 0.0 || x > 100.0) {
              ESP_LOGW("aht20", "Luchtvochtigheid buiten bereik: %.1f%%", x);
              return {};
            }
            return x;

# Text sensor voor leesbare luchtkwaliteit status
text_sensor:
  - platform: template
    name: "Luchtkwaliteit"
    id: air_quality_description
    icon: "mdi:air-filter"
    lambda: |-
      if (isnan(id(ens160_aqi).state)) {
        return {"Onbekend"};
      }
      int aqi = (int)id(ens160_aqi).state;
      
      if (aqi == 1) {
        return {"Uitstekend"};
      } else if (aqi == 2) {
        return {"Goed"};
      } else if (aqi == 3) {
        return {"Matig"};
      } else if (aqi == 4) {
        return {"Slecht"};
      } else if (aqi == 5) {
        return {"Ongezond"};
      } else {
        return {"Onbekend"};
      }
    update_interval: 60s
