# UART configuration for sensor communication
uart:
  id: uart_ld2450
  tx_pin: GPIO20
  rx_pin: GPIO21
  baud_rate: 256000
  parity: NONE
  stop_bits: 1
  rx_buffer_size: 512

ld2450:
  id: ld2450_radar
  uart_id: uart_ld2450

# Numbers to configure zones and presence timeout from Home Assistant
number:
  - platform: ld2450
    ld2450_id: ld2450_radar
    presence_timeout:
      name: "Presence timeout"
    zone_1:
      x1:
        name: "Zone 1 X1"
      x2:
        name: "Zone 1 X2"
      y1:
        name: "Zone 1 Y1"
      y2:
        name: "Zone 1 Y2"
    zone_2:
      x1:
        name: "Zone 2 X1"
      x2:
        name: "Zone 2 X2"
      y1:
        name: "Zone 2 Y1"
      y2:
        name: "Zone 2 Y2"
    zone_3:
      x1:
        name: "Zone 3 X1"
      x2:
        name: "Zone 3 X2"
      y1:
        name: "Zone 3 Y1"
      y2:
        name: "Zone 3 Y2"

binary_sensor:
  - platform: ld2450
    ld2450_id: ld2450_radar
    has_target:
      name: "Presence"
    has_moving_target:
      name: "Movement"
    has_still_target:
      name: "Stationary"
switch:
  - platform: ld2450
    ld2450_id: ld2450_radar
    bluetooth:
      name: "LD2450 Bluetooth"
      restore_mode: ALWAYS_OFF
      disabled_by_default: true
    multi_target:
      name: "Multi Target Tracking"

select:
  - platform: ld2450
    ld2450_id: ld2450_radar
    zone_type:
      name: "Zone Type"

text_sensor:
  - platform: ld2450
    ld2450_id: ld2450_radar
    version:
      name: "LD2450 Firmware"
      disabled_by_default: True
    mac_address:
      name: "LD2450 BT MAC"
      disabled_by_default: True
    target_1:
      direction:
        name: "Target Direction"

sensor:
  - platform: ld2450
    ld2450_id: ld2450_radar
    target_count:
      name: "Target count"
    still_target_count:
      name: "Still Target Count"
    moving_target_count:
      name: "Moving Target Count"
    target_1:
      x:
        name: "Target X"
      y:
        name: "Target Y"
      speed:
        name: "Target Speed"
      angle:
        name: "Target Angle"
      distance:
        name: "Target Distance"
      resolution:
        name: "Target Resolution"
    zone_1:
      target_count:
        name: "Zone 1 Count"
      still_target_count:
        name: "Zone 1 Still Target Count"
      moving_target_count:
        name: "Zone 1 Moving Target Count"
    zone_2:
      target_count:
        name: "Zone 2 Count"
      still_target_count:
        name: "Zone 2 Still Target Count"
      moving_target_count:
        name: "Zone 2 Moving Target Count"
    zone_3:
      target_count:
        name: "Zone 3 Count"
      still_target_count:
        name: "Zone 3 Still Target Count"
      moving_target_count:
        name: "Zone 3 Moving Target Count"