sensor:
  - platform: adc
    pin: GPIO0
    name: "Lichtsterkte"
    id: illuminance
    device_class: illuminance
    unit_of_measurement: lx
    filters:
      - lambda: |-
          return (x / 10000.0) * 2000000.0;