# LDR (Light Dependent Resistor) sensor configuration with improved calibration

substitutions:
  # LDR configuration settings
  ldr_pin: "GPIO0"
  ldr_update_interval: "30s"
  ldr_attenuation: "0db"  # ADC attenuation (0db, 2.5db, 6db, 11db)
  
  # Calibration settings for lux conversion
  ldr_dark_voltage: "0.001"    # Voltage in darkness (V)
  ldr_bright_voltage: "3.3"    # Voltage in bright light (V)
  ldr_max_lux: "2000"          # Maximum lux value
  ldr_gamma: "0.7"             # Gamma correction for responsiveness

sensor:
  - platform: adc
    pin: ${ldr_pin}
    name: "Light Level"
    id: illuminance
    device_class: illuminance
    unit_of_measurement: lx
    accuracy_decimals: 0
    update_interval: ${ldr_update_interval}
    attenuation: ${ldr_attenuation}
    filters:
      # Convert voltage to lux with improved formula
      - lambda: |-
          // Improved lux conversion with gamma correction
          float voltage = x;
          float dark_v = ${ldr_dark_voltage};
          float bright_v = ${ldr_bright_voltage};
          float max_lux = ${ldr_max_lux};
          float gamma = ${ldr_gamma};
          
          // Normalize voltage to 0-1 range
          float normalized = (voltage - dark_v) / (bright_v - dark_v);
          normalized = fmax(0.0, fmin(1.0, normalized));
          
          // Apply gamma correction
          float corrected = pow(normalized, gamma);
          
          // Convert to lux
          float lux = corrected * max_lux;
          
          // Debug logging
          ESP_LOGD("ldr", "Voltage: %.3fV, Normalized: %.3f, Lux: %.0f", voltage, normalized, lux);
          
          return lux;
      # Smoothing filter
      - sliding_window_moving_average:
          window_size: 5
          send_every: 3
      # Sanity check
      - lambda: |-
          if (x < 0) return 0;
          if (x > ${ldr_max_lux}) return ${ldr_max_lux};
          return x;

  # Template sensor for light percentage
  - platform: template
    name: "Light Percentage"
    id: light_percentage
    unit_of_measurement: "%"
    accuracy_decimals: 0
    icon: "mdi:brightness-percent"
    lambda: |-
      if (isnan(id(illuminance).state)) {
        return {};
      }
      float lux = id(illuminance).state;
      float percentage = (lux / ${ldr_max_lux}) * 100.0;
      return fmax(0.0, fmin(100.0, percentage));
    update_interval: 60s

# Binary sensors for light detection
binary_sensor:
  - platform: template
    name: "Daylight"
    id: daylight_detected
    device_class: light
    lambda: |-
      if (isnan(id(illuminance).state)) {
        return {};
      }
      // Daylight detected above 50 lux
      return id(illuminance).state > 50;

# Number for configurable lux thresholds
number:
  - platform: template
    name: "Daylight Threshold"
    id: daylight_threshold
    entity_category: config
    min_value: 10
    max_value: 200
    step: 10
    initial_value: 50
    restore_value: true
    optimistic: true
    icon: "mdi:weather-sunny"
    unit_of_measurement: "lx"
