# LED Air Quality component
# This component manages the LED ring based on air quality

substitutions:
  # Configurable thresholds for eCO2 levels
  eco2_excellent: "600"    # Excellent (blue)
  eco2_good: "800"         # Good (green)
  eco2_fair: "1000"        # Fair (yellow)
  eco2_poor: "1500"        # Poor (orange)
  eco2_bad: "65000"        # Very Poor (red with pulse)
  
  # LED brightness settings
  brightness_min: "0.05"   # Minimum brightness (5%)
  brightness_max: "0.50"   # Maximum brightness (50%)
  lux_scale_factor: "200.0" # Scale factor for light intensity

interval:
  # Main interval for air quality monitoring
  - interval: 60s
    then:
      if:
        condition:
          - wifi.connected
        then:
          - if:
              condition:
                - lambda: 'return isnan(id(ens160_eco2).state);' # Check if eCO2 value is available
              then:
                - light.turn_on:
                    id: led_ring
                    effect: "Rainbow Spinner"
              else:
                - lambda: |-
                    auto call = id(led_ring).turn_on();
                    
                    // Calculate brightness based on light intensity
                    float brightness = (id(illuminance).state / ${lux_scale_factor}) * ${brightness_max} + ${brightness_min};
                    brightness = fmax(${brightness_min}, fmin(1.0, brightness));
                    call.set_brightness(brightness);

                    float eco2 = id(ens160_eco2).state;

                    // LED color based on eCO2 value
                    if (eco2 < ${eco2_excellent}) { // Excellent
                      call.set_effect("None");
                      call.set_rgb(0, 0, 1);  // Blue
                    } else if (eco2 < ${eco2_good}) { // Good
                      call.set_effect("None");
                      call.set_rgb(0, 1, 0);  // Green
                    } else if (eco2 < ${eco2_fair}) { // Fair
                      call.set_effect("None");
                      call.set_rgb(1, 1, 0);  // Yellow
                    } else if (eco2 < ${eco2_poor}) { // Poor
                      call.set_effect("None");
                      call.set_rgb(1, 0.5, 0);  // Orange
                    } else if (eco2 < ${eco2_bad}) { // Very Poor
                      call.set_rgb(1, 0, 0);  // Red
                      call.set_effect("Pulse");
                    } else { // Extremely Poor
                      call.set_rgb(1, 0, 0);  // Red
                      call.set_effect("Strobe");
                    }

                    call.perform();

  # Quick check interval for responsiveness
  - interval: 5s
    then:
      - if:
          condition:
            - wifi.connected
          then:
            - if:
                condition:
                  - lambda: 'return isnan(id(ens160_eco2).state);' # Check if eCO2 value is available
                then:
                  - light.turn_on:
                      id: led_ring
                      effect: "Rainbow Spinner"
