substitutions:
  device_description: ${friendly_name} made by RFinkers, version ${project.version}

esphome:
  name: ${name}
  friendly_name: ${friendly_name}
  name_add_mac_suffix: true
  comment: '${device_description}'
  project:
    name: "rfinkers.${name}"

preferences:
  flash_write_interval: 120min

esp32:
  board: esp32-c3-devkitm-1
  framework:
    type: arduino

logger:
  level: ${log_level}
  # baud_rate: 0  # Disable logging over UART (improv_serial require the logger to be enabled)

safe_mode:

i2c:
  sda: GPIO6
  scl: GPIO7
  scan: true

sensor:
  - platform: uptime
    id: esp_uptime

text_sensor:
  - platform: version
    name: "ESPHome Version"
    hide_timestamp: true

button:
  - platform: restart
    name: "Restart device"
    entity_category: diagnostic
  - platform: factory_reset
    name: "Factory reset"
    entity_category: diagnostic
    disabled_by_default: True
  - platform: safe_mode
    name: "Safe Mode"
    entity_category: diagnostic
    disabled_by_default: True